INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (1, 'Aguascalientes', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (2, 'Baja California', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (3, 'Baja California Sur', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (4, 'Campeche', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (7, 'Chiapas', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (8, 'Chihuahua', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (5, 'Coahuila de Zaragoza', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (6, 'Colima', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (10, 'Durango', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (15, 'Estado de México', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (11, 'Guanajuato', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (12, 'Guerrero', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (13, 'Hidalgo', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (14, 'Jalisco', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (16, 'Michoacán de Ocampo', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (17, 'Morelos', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (18, 'Nayarit', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (19, 'Nuevo León', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (20, 'Oaxaca', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (21, 'Puebla', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (22, 'Querétaro', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (23, 'Quintana Roo', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (24, 'San Luis Potosí', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (25, 'Sinaloa', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (26, 'Sonora', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (27, 'Tabasco', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (28, 'Tamaulipas', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (29, 'Tlaxcala', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (30, 'Veracruz de Ignacio de la Llave', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (31, 'Yucatán', '', '');
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (32, 'Zacatecas', '', '');  
INSERT INTO z_estados(ide, estado, descripcion, aux) VALUES (9, 'Ciudad de México', '', '');  

